//
// Created by jacky on 2019/5/18.
//

#ifndef ANOTHER_CARD_GAME_ACG_ACCOUNTSYSTEMPACKAGE_H
#define ANOTHER_CARD_GAME_ACG_ACCOUNTSYSTEMPACKAGE_H


class AccountSystemPackage {

};


#endif //ANOTHER_CARD_GAME_ACG_ACCOUNTSYSTEMPACKAGE_H
