//
// Created by jacky on 2019/6/2.
//

#ifndef ANOTHER_CARD_GAME_ACG_ROOMMODE_H
#define ANOTHER_CARD_GAME_ACG_ROOMMODE_H
enum RoomMode { SINGLE_ROOM=0, ONEONONE_ROOM, LADDER_ROOM, ROOMMODE_COUNT};
#endif //ANOTHER_CARD_GAME_ACG_ROOMMODE_H
